<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Pkcs11Interop" Version="5.3.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="certificates\entrust\intermediate.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="certificates\entrust\root.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="certificates\sectigo\intermediate.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="certificates\sectigo\root.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.dancert.da.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.dancert.de.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.dancert.en.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.danfysik.da.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.danfysik.de.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.danfysik.en.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.ti.da.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.ti.de.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logos\stamp.ti.en.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="certificates\entrust\" />
  </ItemGroup>

</Project>
